# Generated by Django 5.2.12 on 2026-03-28 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('sharpe_ratio', models.FloatField(default=0.0)),
                ('total_signals', models.IntegerField(default=0)),
                ('correct_signals', models.IntegerField(default=0)),
                ('current_weight', models.FloatField(default=0.333)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('agent_type', 'symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AgentSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('technical', 'Technical Agent'), ('macro', 'Macro Agent'), ('sentiment', 'Sentiment Agent')], max_length=20)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('signal', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('NEUTRAL', 'Neutral')], max_length=10)),
                ('confidence', models.FloatField()),
                ('reasoning', models.TextField()),
                ('features_used', models.JSONField(default=dict)),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent_type', 'symbol', '-timestamp'], name='agents_agen_agent_t_8df3de_idx'), models.Index(fields=['symbol', '-timestamp'], name='agents_agen_symbol_2abf47_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoordinatorDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decision', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('NEUTRAL', 'Neutral')], max_length=10)),
                ('confidence', models.FloatField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('weights', models.JSONField(default=dict)),
                ('reasoning', models.TextField()),
                ('volatility_regime', models.CharField(default='normal', max_length=20)),
                ('macro_signal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='macro_decisions', to='agents.agentsignal')),
                ('sentiment_signal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_decisions', to='agents.agentsignal')),
                ('technical_signal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_decisions', to='agents.agentsignal')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='agents_coor_symbol_7a313f_idx'), models.Index(fields=['-timestamp'], name='agents_coor_timesta_2b7b9d_idx')],
            },
        ),
    ]
