"""
LangChain Service for Forex Alpha
Provides AI-powered explanation of signals and market analysis.
Falls back to a rule-based explanation when no API key is configured.
"""

import os
from typing import Dict, List, Optional
from datetime import datetime

# LangChain imports (graceful fallback)
try:
    from langchain_openai import ChatOpenAI
    from langchain.memory import ConversationBufferMemory
    from langchain.chains import ConversationChain
    from langchain.prompts import (
        ChatPromptTemplate,
        HumanMessagePromptTemplate,
        SystemMessagePromptTemplate,
        MessagesPlaceholder,
    )
    from langchain.schema import HumanMessage, SystemMessage
    LANGCHAIN_AVAILABLE = True
except ImportError:
    try:
        from langchain.chat_models import ChatOpenAI
        from langchain.memory import ConversationBufferMemory
        from langchain.chains import ConversationChain
        from langchain.prompts import (
            ChatPromptTemplate,
            HumanMessagePromptTemplate,
            SystemMessagePromptTemplate,
            MessagesPlaceholder,
        )
        from langchain.schema import HumanMessage, SystemMessage
        LANGCHAIN_AVAILABLE = True
    except ImportError:
        LANGCHAIN_AVAILABLE = False


SYSTEM_PROMPT = """You are ForexAlpha AI, an expert quantitative analyst and FX trader.
You help users understand trading signals generated by a multi-agent system that combines:
- Technical Analysis Agent (RSI, MACD, Bollinger Bands, moving averages)
- Fundamental Analysis Agent (economic indicators, interest rates, GDP)
- Sentiment Analysis Agent (news sentiment, market positioning)
- RLM Agent (Reinforcement Learning Model trained on price history)

When given signal data, you:
1. Explain in plain language why the signal was generated
2. Identify key supporting and contradicting factors
3. Provide risk considerations
4. Suggest relevant economic events to watch
5. Keep answers concise and professional

Always remind users that signals are educational and not financial advice.
"""


class LangChainService:
    """Wraps LangChain for multi-turn market analysis conversations."""

    def __init__(self):
        self.api_key = os.getenv('OPENAI_API_KEY', '')
        self._sessions: Dict[str, object] = {}  # session_id -> chain

    # ──────────────────────────────────────────────────
    def _build_chain(self, session_id: str):
        if not LANGCHAIN_AVAILABLE or not self.api_key:
            return None

        llm = ChatOpenAI(
            model_name='gpt-4o-mini',
            temperature=0.3,
            openai_api_key=self.api_key,
        )
        memory = ConversationBufferMemory(return_messages=True)
        prompt = ChatPromptTemplate.from_messages([
            SystemMessagePromptTemplate.from_template(SYSTEM_PROMPT),
            MessagesPlaceholder(variable_name='history'),
            HumanMessagePromptTemplate.from_template('{input}'),
        ])
        chain = ConversationChain(llm=llm, memory=memory, prompt=prompt)
        self._sessions[session_id] = chain
        return chain

    def _get_chain(self, session_id: str):
        if session_id not in self._sessions:
            return self._build_chain(session_id)
        return self._sessions[session_id]

    # ──────────────────────────────────────────────────
    def explain_signal(self, session_id: str, signal: Dict,
                       market_context: Optional[Dict] = None) -> str:
        """
        Generate a natural-language explanation of a trading signal.

        Parameters
        ----------
        session_id : str
        signal : dict  – the signal dict from ensemble / RLM
        market_context : dict – optional extra market data

        Returns
        -------
        str  explanation text
        """
        context_text = ''
        if market_context:
            context_text = f"""
Market context:
- Symbol: {market_context.get('symbol', signal.get('symbol', 'N/A'))}
- Current price: {market_context.get('current_price', 'N/A')}
- 1-day change: {market_context.get('price_change_1d', 'N/A')}
- Volatility (ATR): {market_context.get('atr', 'N/A')}
- Volume trend: {market_context.get('volume_trend', 'N/A')}
"""

        prompt_text = f"""
Analyse this trading signal and explain it clearly:

Signal:
- Symbol: {signal.get('symbol', 'N/A')}
- Direction: {signal.get('direction', 'N/A')}
- Confidence: {signal.get('confidence', 0):.1%}
- Agent: {signal.get('agent_name', 'N/A')}
- Reasoning: {signal.get('reasoning', 'N/A')}
{context_text}

Please explain:
1. Why this signal was generated
2. Key risk factors
3. What to watch next
"""
        chain = self._get_chain(session_id)
        if chain is None:
            return self._rule_based_explanation(signal)

        try:
            response = chain.predict(input=prompt_text)
            return response
        except Exception as e:
            return self._rule_based_explanation(signal) + f"\n\n(LangChain error: {e})"

    # ──────────────────────────────────────────────────
    def chat(self, session_id: str, message: str) -> str:
        """
        Free-form chat within a session.
        """
        chain = self._get_chain(session_id)
        if chain is None:
            return (
                "LangChain / OpenAI is not configured. "
                "Set OPENAI_API_KEY in your .env file to enable the AI assistant."
            )
        try:
            return chain.predict(input=message)
        except Exception as e:
            return f"AI assistant error: {e}"

    # ──────────────────────────────────────────────────
    @staticmethod
    def _rule_based_explanation(signal: Dict) -> str:
        """Fallback explanation generated from signal data without LLM."""
        direction = signal.get('direction', 'HOLD')
        confidence = signal.get('confidence', 0)
        agent = signal.get('agent_name', 'Unknown')
        reasoning = signal.get('reasoning', '')

        if direction == 'BUY':
            sentiment = 'bullish'
            action = 'consider entering a long position'
        elif direction == 'SELL':
            sentiment = 'bearish'
            action = 'consider entering a short position'
        else:
            sentiment = 'neutral'
            action = 'remain on the sidelines'

        conf_label = (
            'high' if confidence > 0.7
            else 'moderate' if confidence > 0.4
            else 'low'
        )

        return (
            f"The {agent} has generated a **{direction}** signal for "
            f"{signal.get('symbol', 'this pair')} with **{conf_label} confidence** "
            f"({confidence:.1%}).\n\n"
            f"**Analysis:** {reasoning}\n\n"
            f"**Interpretation:** Market conditions appear {sentiment}. "
            f"Based on the model's assessment, you may {action}.\n\n"
            f"**Risk Notice:** Always use proper position sizing and stop-losses. "
            f"This signal is educational and not financial advice.\n\n"
            f"*Configure OPENAI_API_KEY in .env to enable full AI explanations.*"
        )


# Singleton
_service: Optional[LangChainService] = None


def get_langchain_service() -> LangChainService:
    global _service
    if _service is None:
        _service = LangChainService()
    return _service
