# Generated by Django 5.2.12 on 2026-03-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=50)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('is_passing', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['source', 'metric_name', '-timestamp'], name='validation__source_958fd5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ValidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('timeseries', 'Time Series'), ('macro', 'Macro Data'), ('news', 'News Data')], max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('issues_found', models.IntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
                ('records_checked', models.IntegerField(default=0)),
                ('missing_count', models.IntegerField(default=0)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('anomaly_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['report_type', '-timestamp'], name='validation__report__94e1e5_idx'), models.Index(fields=['symbol', '-timestamp'], name='validation__symbol_16d162_idx')],
            },
        ),
    ]
