# Generated by Django 5.2.12 on 2026-03-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(db_index=True, max_length=50)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pnl', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('was_correct', models.BooleanField(default=False)),
                ('signal', models.CharField(max_length=10)),
                ('reasoning', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'agent_performance_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent_name', '-timestamp'], name='agent_perfo_agent_n_c65777_idx'), models.Index(fields=['symbol', '-timestamp'], name='agent_perfo_symbol_b51bcd_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('component', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('metrics', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['component', '-timestamp'], name='monitoring__compone_1f7cc8_idx')],
            },
        ),
    ]
