# Generated by Django 5.2.12 on 2026-03-28 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('strategy_config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_return', models.FloatField(null=True)),
                ('sharpe_ratio', models.FloatField(null=True)),
                ('max_drawdown', models.FloatField(null=True)),
                ('win_rate', models.FloatField(null=True)),
                ('profit_factor', models.FloatField(null=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('metrics', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', '-created_at'], name='backtesting_symbol_ef70fb_idx'), models.Index(fields=['status', '-created_at'], name='backtesting_status_09349e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(null=True)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField(null=True)),
                ('size', models.FloatField(default=1.0)),
                ('pnl', models.FloatField(null=True)),
                ('pnl_percent', models.FloatField(null=True)),
                ('decision_confidence', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('entry_reasoning', models.TextField(blank=True)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtesting.backtestrun')),
            ],
            options={
                'ordering': ['entry_time'],
                'indexes': [models.Index(fields=['backtest', 'entry_time'], name='backtesting_backtes_a64aea_idx')],
            },
        ),
    ]
