# Generated by Django 5.2.12 on 2026-03-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MacroFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('interest_rate_diff', models.FloatField(null=True)),
                ('policy_rate_diff', models.FloatField(null=True)),
                ('inflation_diff', models.FloatField(null=True)),
                ('surprise_metric', models.FloatField(null=True)),
                ('yield_spread', models.FloatField(null=True)),
                ('risk_sentiment', models.FloatField(null=True)),
                ('gdp_growth_diff', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['currency_pair', '-date'], name='features_ma_currenc_789564_idx')],
                'unique_together': {('currency_pair', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SentimentFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('currency_mentioned', models.CharField(db_index=True, max_length=10)),
                ('sentiment_score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('relevance_score', models.FloatField()),
                ('news_volume_1h', models.IntegerField(default=0)),
                ('news_volume_24h', models.IntegerField(default=0)),
                ('source', models.CharField(max_length=100)),
                ('article_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['currency_mentioned', '-timestamp'], name='features_se_currenc_f147d3_idx'), models.Index(fields=['-timestamp'], name='features_se_timesta_79ee27_idx')],
            },
        ),
        migrations.CreateModel(
            name='TechnicalFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('rsi_14', models.FloatField(null=True)),
                ('rsi_28', models.FloatField(null=True)),
                ('macd', models.FloatField(null=True)),
                ('macd_signal', models.FloatField(null=True)),
                ('macd_diff', models.FloatField(null=True)),
                ('bb_upper', models.FloatField(null=True)),
                ('bb_middle', models.FloatField(null=True)),
                ('bb_lower', models.FloatField(null=True)),
                ('bb_width', models.FloatField(null=True)),
                ('bb_position', models.FloatField(null=True)),
                ('atr_14', models.FloatField(null=True)),
                ('rolling_vol_20', models.FloatField(null=True)),
                ('rolling_vol_60', models.FloatField(null=True)),
                ('trend_slope_20', models.FloatField(null=True)),
                ('trend_slope_60', models.FloatField(null=True)),
                ('distance_to_support', models.FloatField(null=True)),
                ('distance_to_resistance', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='features_te_symbol_4396dd_idx')],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
    ]
